### ISSUE TITLE
SPARQL: check syntax for triplestoreswap

### ISSUE THREAD

**Issue by jefferya** [cwrc/islandora_cwrc_credit_visualization#1]
To test:
* populate via drush bootstrap
* populate via drush by date

https://github.com/cwrc/islandora_cwrc_credit_visualization/blob/b8016d292308600daa106d226cced51ccd4bb999/islandora_cwrc_credit_visualization.drush.inc#L71-L80

https://github.com/cwrc/islandora_cwrc_credit_visualization/blob/b8016d292308600daa106d226cced51ccd4bb999/islandora_cwrc_credit_visualization.drush.inc#L111-L122

**Comment by joelacummings** [comment]
This looks ok provided everything between <> brackets represent the full URI.

**Comment by jefferya** [comment]
ToDo:
* add: `PREFIX fedora-model: <info:fedora/fedora-system:def/model#>`
* add: `PREFIX fedora-view: <info:fedora/fedora-system:def/view#>`
* remove angle brackets: `fedora-model:label` and `fedora-model:hasModel`

**Comment by jefferya** [comment]
ToDo:
* add: PREFIX fedora-model: `<info:fedora/fedora-system:def/model#>`
* add: PREFIX fedora-view: <info:fedora/fedora-system:def/view#>
* remove angle brackets: `fedora-model:label` and `fedora-model:hasModel`
